version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    networks:
      spark-network:
        aliases:
          - mongodb

  jupyter:
    build: .
    container_name: jupyter
    ports:
      - "8888:8888"
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    volumes:
      - ./notebooks:/home/jovyan/work
    depends_on:
      - mongodb
    networks:
      - spark-network
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser

  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      SPARK_MODE: master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master --host spark-master --port 7077
    networks:
      - spark-network
    volumes:
      - ./notebooks:/home/jovyan/work

  spark-worker:
    image: apache/spark:3.5.0
    container_name: spark-worker
    ports:
      - "8081:8081"
    environment:
      SPARK_MASTER_HOST: spark-master
      SPARK_MASTER_PORT: 7077
      SPARK_WORKER_MEMORY: 4G
      SPARK_WORKER_CORES: 4
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
      - mongodb
    networks:
      - spark-network
    volumes:
      - ./notebooks:/home/jovyan/work

volumes:
  mongodb_data:

networks:
  spark-network:
    driver: bridge
